#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 21 16:53:36 2021

@author: adisrikanth
"""

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""


import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import math

x = np.arange(0, 1, 0.015)
y = np.arange(0, 1, 0.015)


X, Y = np.meshgrid(x, y)

nu = (np.log(3150)) + (4 * np.log(X)) + (2 * np.log(Y)) + (4 * np.log(1 - X - Y))


fig = plt.figure()
ax = Axes3D(fig)
ax.plot_surface(X, Y, nu)
plt.xlabel('theta')
plt.ylabel('alpha')
plt.show()


        
    